Repository dataforgoodfr/13_pollution_eau, pull requests merged in 2025-04, with the labels that each got.

#132 Feature/udi pmtiles
  .github/workflows/synchronize_db.yaml
  .github/workflows/test_pipelines.yaml
  README.md
  dbt_/models/sources/__sources.yml
  dbt_/models/staging/communes/_communes_models.yml
  dbt_/models/staging/communes/stg_communes__opendatasoft.sql
  dbt_/models/staging/communes/stg_communes__opendatasoft_json.sql
  dbt_/models/staging/udi/_udi_models.yml
  dbt_/models/staging/udi/stg_udi_json.sql
  pipelines/notebooks/test.atlasante_udi.ipynb
  pipelines/notebooks/test_atlasante_udi.ipynb
  pipelines/notebooks/test_geojson_from_db.ipynb
  pipelines/notebooks/test_new_geojson.ipynb
  pipelines/notebooks/test_opendatasoft_communes.ipynb
  pipelines/tasks/build_database.py
  pipelines/tasks/client/geojson_processor.py
  pipelines/tasks/client/opendatasoft_client.py
  pipelines/tasks/client/pmtiles_processor.py
  pipelines/tasks/config/config_geojson.py
  pipelines/tasks/generate_pmtiles.py
Labels: team-data-eng

#110 WIP Filtre commune v3
  webapp/components/PollutionMap.tsx
  webapp/components/PollutionMapBase.tsx
  webapp/components/PollutionMapSearchBox.tsx
Labels: team-webdev

#128 Feature/dropdown
  webapp/app/globals.css
  webapp/components/PollutionMap.tsx
  webapp/components/PollutionMapFilters.tsx
  webapp/components/PollutionMapSearchBox.tsx
  webapp/lib/polluants.ts
  webapp/package-lock.json
  webapp/package.json
Labels: team-webdev

#140 ✨ Ajouter un composant de légende
  webapp/components/PollutionMap.tsx
  webapp/components/PollutionMapLegend.tsx
  webapp/components/ui/hamburger-button.tsx
Labels: team-webdev

#161 Analyst/vinca cvm add file ref
  dbt_/models/intermediate/cvm/int__resultats_cvm_commune_annuel.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_commune_dernier.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_udi_annuel.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_udi_dernier.sql
Labels: team-data-analyst

#160 Side panel and legend visibility based on screen size
  webapp/components/PollutionMap.tsx
Labels: team-webdev

#142 Analyst/vinca substances indus
  analytics/notebooks/resultats_sub_indus.ipynb
  dbt_/models/intermediate/int__union_resultats_commune.sql
  dbt_/models/intermediate/int__union_resultats_udi.sql
  dbt_/models/intermediate/sub_indus/_int__sub_indus_models.yaml
  dbt_/models/intermediate/sub_indus/int__resultats_sub_indus_commune_annuel.sql
  dbt_/models/intermediate/sub_indus/int__resultats_sub_indus_commune_dernier.sql
  dbt_/models/intermediate/sub_indus/int__resultats_sub_indus_udi_annuel.sql
  dbt_/models/intermediate/sub_indus/int__resultats_sub_indus_udi_dernier.sql
  dbt_/tests/test_sub_indus_results.sql
  dbt_/tests/test_valeur_saniraire_2.sql
Labels: team-data-analyst

#163 feat: use new file GF pfas udi dernier
  dbt_/models/intermediate/pfas/_int__pfas_models.yml
  dbt_/models/intermediate/pfas/int__resultats_pfas_udi_dernier.sql
  dbt_/tests/test_pfas_results.sql
  dbt_/tests/tests_int__resultats_pfas_udi_dernier.sql
  webapp/lib/polluants.ts
Labels: team-data-analyst

#153 UDI Endpoint - Connect to DB
  webapp/app/api/udi/[udi_id]/route.ts
  webapp/app/lib/mock-data.ts
Labels: team-webdev

#148 Analyst/lounes_pfas_udi_annuel
  dbt_/models/intermediate/pfas/_int__pfas_models.yml
  dbt_/models/intermediate/pfas/int__resultats_pfas_udi_annuel.sql
  dbt_/models/intermediate/pfas/int__resultats_pfas_udi_dernier.sql
  dbt_/tests/test__coverage_20pfas_4pfas_98pct.sql
  dbt_/tests/test_pfas_results.sql
Labels: team-data-analyst

#164 Analyst/lounes tous polluants udi dernier
  dbt_/models/intermediate/tous/_int__tous_models.yml
  dbt_/models/intermediate/tous/int__resultats_tous_udi_dernier.sql
  dbt_/models/website/_web__models.yml
  dbt_/models/website/web__resultats_udi.sql
  dbt_/tests/test_tous_results.sql
  webapp/lib/polluants.ts
Labels: team-data-analyst
