Repository dataforgoodfr/13_pollution_eau, pull requests merged in 2025-02, with the labels that each got.

#9 Feature/collecte de plusieurs annees pour le dataset edc
  analytics/notebooks/exemple.ipynb
  pipelines/tasks/_common.py
  pipelines/tasks/_config_edc.py
  pipelines/tasks/build_database.py
Labels: team-data-eng

#6 Feat/store data s3 scaleway
  .github/workflows/synchronize_db.yaml
  README.md
  pipelines/config/.env.example
  pipelines/config/config.py
  pipelines/run.py
  pipelines/tasks/download_database.py
  pipelines/tasks/upload_database.py
  pipelines/utils/utils.py
Labels: team-data-eng

#12 Notebook Exemples
  analytics/notebooks/exemple/exemple_duckdb.ipynb
  analytics/notebooks/exemple/exemple_ibis.ipynb
  pyproject.toml
  uv.lock
Labels: team-data-eng

#10 Analyse seuil zeynep
  analytics/notebooks/etude_cvm.ipynb
  pyproject.toml
  uv.lock
Labels: team-data-analyst

#11 Feature/request by specific year
  README.md
  pipelines/config/.env.example
  pipelines/run.py
  pipelines/tasks/build_database.py
  pipelines/tasks/download_database.py
  pipelines/tasks/upload_database.py
Labels: team-data-eng

#25 build_database.py / Add option to drop EDC tables
  pipelines/run.py
  pipelines/tasks/build_database.py
Labels: team-data-eng

#26 update documentation
  README.md
  pipelines/tasks/build_database.py
Labels: team-data-eng

#23 Setup dbt
  .gitignore
  README.md
  dbt_/.gitignore
  dbt_/analyses/.gitkeep
  dbt_/dbt_project.yml
  dbt_/macros/.gitkeep
  dbt_/models/staging/edc/_edc__models.yml
  dbt_/models/staging/edc/_edc__sources.yml
  dbt_/models/staging/edc/stg_edc__communes.sql
  dbt_/models/staging/edc/stg_edc__prevelevements.sql
  dbt_/models/staging/edc/stg_edc__resultats.sql
  dbt_/models/staging/edc/val_traduite__docs.md
  dbt_/packages.yml
  dbt_/profiles.yml
  dbt_/seeds/.gitkeep
  dbt_/snapshots/.gitkeep
  dbt_/tests/.gitkeep
  pipelines/tasks/build_database.py
  pyproject.toml
Labels: team-data-eng

#31 Add cron to synchronize db workflow
  .github/workflows/synchronize_db.yaml
Labels: team-data-eng

#30 build_database.py/ Ajout d'une barre de progression lors de l'upload des données en base
  pipelines/tasks/build_database.py
  pyproject.toml
  uv.lock
Labels: team-data-eng

#27 Feat: Upload database.duckdb with public visibility
  README.md
  pipelines/run.py
  pipelines/tasks/_common.py
  pipelines/tasks/build_database.py
  pipelines/tasks/download_database_https.py
  pipelines/tasks/upload_database.py
  pipelines/utils/storage_client.py
Labels: team-data-eng

#34 Feature : ajout d'une tâche VS Code pour télécharger la base de données
  .vscode/tasks.json
Labels: team-data-eng

#24 Feature/Mise à jour automatique de la donnée 1/2
  README.md
  analytics/notebooks/extraction_parametres.ipynb
  pipelines/run.py
  pipelines/tasks/_config_edc.py
  pipelines/tasks/build_database.py
  pipelines/utils/utils.py
  pyproject.toml
Labels: team-data-eng

#37 Feature: Add a github action to deploy dbt docs on a github page
  .github/workflows/deploy_dbt_docs_to_github_page.yml
Labels: team-data-eng

#17 feature/duckdb: POC duck db node api
  webapp/app/api/db-example/route.ts
  webapp/app/duckdb-example/loading.tsx
  webapp/app/duckdb-example/page.tsx
  webapp/app/lib/data.ts
  webapp/app/lib/duckdb.ts
  webapp/next.config.ts
  webapp/package-lock.json
  webapp/package.json
Labels: team-webdev

#19 EDA seuils P1
  analytics/notebooks/Lise-AJT_P1_EXPLO_SEUILS.ipynb
Labels: team-data-analyst

#16 Analyse des bases de données de communes, contours des IRIS, communes et départements
  analytics/notebooks/Exploration communes.ipynb
Labels: team-data-analyst

#40 notebook for Explo - 1,4 dioxane
  analytics/notebooks/etude_pfas_thomas.ipynb
  analytics/notebooks/explo_14_dioxane.ipynb
Labels: team-data-analyst

#53 Ajout de la table de mapping des catégories de polluants
  dbt_/seeds/mapping_categories.csv
  dbt_/seeds/schema.yml
Labels: team-data-eng

#59 Fix: changement des valeurs acceptables pour `plvconformitereferencechim` dans dbt
  dbt_/models/staging/edc/_edc__models.yml
Labels: bug, team-data-eng

#52 Refactoring : fusion des tâches `download_database` et `download_database_https`
  .vscode/tasks.json
  README.md
  pipelines/run.py
  pipelines/tasks/download_database.py
  pipelines/tasks/download_database_https.py
  pipelines/utils/storage_client.py
Labels: team-data-eng

#39 [CI debug] Ajout d'un test de bout-en-bout pour les commandes de pipelines (build/download/upload database)
  .github/workflows/test_pipelines.yaml
  .vscode/settings.json
  README.md
  pipelines/test_pipelines.py
  pyproject.toml
  uv.lock
Labels: team-data-eng

#64 add error handling for ObjectStorangeClient
  pipelines/utils/storage_client.py
Labels: team-data-eng

#47 Feature/add cog communes dataset
  analytics/notebooks/Exploration communes.ipynb
  analytics/notebooks/exemple.ipynb
  analytics/notebooks/exemple/exemple_duckdb.ipynb
  analytics/notebooks/exemple/exemple_ibis.ipynb
  analytics/notebooks/explo_14_dioxane.ipynb
  analytics/notebooks/extraction_parametres.ipynb
  dbt_/models/sources/__sources.yml
  dbt_/models/staging/communes/_communes_models.yml
  dbt_/models/staging/communes/stg_communes__cog.sql
  dbt_/models/staging/communes/stg_communes__laposte.sql
  pipelines/tasks/build_database.py
  pipelines/tasks/client/datagouv_client.py
  pipelines/tasks/client/duckdb_client.py
  pipelines/tasks/client/https_client.py
  pipelines/tasks/client/insee_client.py
  pipelines/tasks/config/common.py
  pipelines/tasks/config/config_edc.py
  pipelines/tasks/config/config_insee.py
  pipelines/tasks/config/config_laposte.py
  pipelines/tasks/download_database.py
  pipelines/tasks/upload_database.py
  pipelines/utils/utils.py
Labels: team-data-eng

#70 Vinca tache132 limite de qualité
  analytics/notebooks/Tache132_Etude_limite_de_qualite.ipynb
Labels: team-data-analyst

#72 add laposte data
  dbt_/models/staging/communes/_communes_models.yml
  dbt_/models/staging/communes/stg_communes__laposte.sql
  pipelines/tasks/build_database.py
  pipelines/tasks/client/datagouv_client.py
  pipelines/tasks/client/duckdb_client.py
  pipelines/tasks/client/https_to_duckdb_client.py
  pipelines/tasks/config/config_insee.py
  pipelines/tasks/config/config_laposte.py
  pipelines/utils/utils.py
Labels: team-data-eng

#57 Setup shadcn
  webapp/app/globals.css
  webapp/components.json
  webapp/components/ui/button.tsx
  webapp/components/ui/card.tsx
  webapp/components/ui/command.tsx
  webapp/components/ui/dialog.tsx
  webapp/components/ui/hover-card.tsx
  webapp/components/ui/input.tsx
  webapp/components/ui/popover.tsx
  webapp/components/ui/scroll-area.tsx
  webapp/components/ui/select.tsx
  webapp/lib/utils.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/tailwind.config.ts
Labels: team-webdev
