Repository dataforgoodfr/13_pollution_eau, pull requests merged in 2025-03, with the labels that each got.

#76 download geojson data and update it with resultat_communes data
  dbt_/models/analytics/_ana__models.yml
  pipelines/notebooks/test_geojson.ipynb
  pipelines/tasks/client/https_client.py
  uv.lock
Labels: team-data-eng

#84 Analysis/explo_contours_udi
  analytics/notebooks/exploration_udi.ipynb
Labels: team-data-analyst

#48 Analysis/new datasource
  analytics/notebooks/bdd_edr_cap.ipynb
  analytics/notebooks/bdd_edr_ttp.ipynb
  analytics/notebooks/bdd_edr_udi.ipynb
Labels: team-data-analyst

#46 Tache110 "Polluants le plus souvent non conformes"
  analytics/notebooks/Tache110_Polluants_le_plus_souvent_non_conformes.ipynb
Labels: team-data-analyst

#41 analyse pour récupérer/filtrer rapidement les résultats concernant les PFAS
  analytics/notebooks/recuperer_rapidement_pfas.ipynb
Labels: team-data-analyst

#93 Tache165 join mapping_categories and edc_resultats
  analytics/notebooks/Tache165_Join-resultat-categorie.ipynb
  dbt_/models/intermediate/_int__models.yml
  dbt_/models/intermediate/int__mapping_category_simple.sql
Labels: team-data-analyst

#90 Filtre commune v2
  webapp/app/globals.css
  webapp/components/PollutionMap.tsx
  webapp/components/PollutionMapBase.tsx
  webapp/components/PollutionMapSearchBox.tsx
  webapp/package-lock.json
  webapp/package.json
Labels: team-webdev

#100 Dbt models update
  dbt_/models/intermediate/_int__models.yml
  dbt_/models/intermediate/int__lien_cdreseau_refreneceprel.sql
  dbt_/models/intermediate/int__lien_commune_cdreseau.sql
  dbt_/models/intermediate/int__resultats_udi_communes.sql
  dbt_/models/staging/edc/_edc__models.yml
  dbt_/models/staging/edc/stg_edc__communes.sql
  dbt_/models/staging/edc/stg_edc__prevelevements.sql
  dbt_/models/staging/edc/stg_edc__resultats.sql
Labels: team-data-analyst

#98 Feature/geo json
  dbt_/seeds/mapping_categories.csv
  pipelines/config/config.py
  pipelines/notebooks/test_geojson.ipynb
  pipelines/notebooks/test_new_geojson.ipynb
  pipelines/run.py
  pipelines/tasks/client/opendatasoft_client.py
  pipelines/tasks/config/config_geojson.py
  pipelines/tasks/download_geojson.py
  pipelines/tasks/generate_geojson.py
  pipelines/tasks/geojson_processor.py
  pipelines/tasks/upload_geojson.py
  pyproject.toml
  uv.lock
Labels: team-data-eng

#112 Feature/gesontopmile
  .github/workflows/synchronize_db.yaml
  README.md
  pipelines/config/config.py
  pipelines/run.py
  pipelines/tasks/client/pmtiles_processor.py
  pipelines/tasks/download_pmtiles.py
  pipelines/tasks/generate_pmtiles.py
  pyproject.toml
  uv.lock
Labels: team-data-eng

#102 Vinca tache178 update table cvm
  analytics/notebooks/Check_rqana_valtraduite.ipynb
  analytics/notebooks/TEST_ana__resultats_udi.ipynb
  analytics/notebooks/cvm_calcul_annuel_all_communes
  analytics/notebooks/resultats_cvm_udi_annuel.ipynb
  analytics/notebooks/resultats_cvm_udi_annuel_add percent.ipynb
  analytics/notebooks/resultats_cvm_udi_dernier.ipynb
  dbt_/models/analytics/_ana__models.yml
  dbt_/models/analytics/ana__resultats_udi.sql.notready
  dbt_/models/intermediate/_int__models.yml
  dbt_/models/intermediate/all/_int_all__models.yml
  dbt_/models/intermediate/all/int__resultats_udi_annuel.sql.notready
  dbt_/models/intermediate/all/int__resultats_udi_dernier.sql.notready
  dbt_/models/intermediate/cvm/_int__cvm_models.yaml
  dbt_/models/intermediate/cvm/int__resultats_cvm_commune_annuel.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_commune_dernier.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_udi_annuel.sql
  dbt_/models/intermediate/cvm/int__resultats_cvm_udi_dernier.sql
  dbt_/tests/test_cvm_results.sql
Labels: team-data-analyst

#115 Task/177_results-pfas_data-model
  analytics/notebooks/Tache177_resultats-pfas-dbt-model.ipynb
  dbt_/models/intermediate/_int__models.yml
  dbt_/models/intermediate/pfas/_int__pfas_models.yml
  dbt_/models/intermediate/pfas/int__resultats_pfas_udi_dernier.sql
  dbt_/tests/tests_int__resultats_pfas_udi_dernier.sql
Labels: team-data-analyst

#99 Tache - Carto - Gestion raccourcis DROM
  webapp/components/MapZoneSelector.tsx
  webapp/components/PollutionMap.tsx
  webapp/components/PollutionMapBase.tsx
  webapp/components/ui/tooltip.tsx
  webapp/package-lock.json
  webapp/package.json
  webapp/public/drom-guadeloupe.svg
  webapp/public/drom-guyane.svg
  webapp/public/drom-martinique.svg
  webapp/public/drom-mayotte.svg
  webapp/public/drom-metropole.svg
  webapp/public/drom-reunion.svg
  webapp/tailwind.config.ts
Labels: team-webdev

#113 Feature - UDI endpoint with mock data
  webapp/app/api/udi/[udi_id]/route.ts
  webapp/app/globals.css
  webapp/app/lib/mock-data.ts
Labels: team-webdev
